version: '3.8'

services:
  web:
    container_name: web
    build: ./infra/web
    ports:
      - '80:80'
    volumes:
      - ./eisys:/var/www/html
    depends_on:
      - mysql
    tty: true
    stdin_open: true
    privileged: true

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./infra/mysql:/var/lib/mysql
volumes:
  mysql: